# config/_default/languages.en.toml

title = "My awesome website"

[author]
name = "Daniel Kehyayan"
image = "img/author.jpg"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { github = "https://github.com/DVK02" }
]
