# config/_default/menus.toml
[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10


[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "Categories"
  parent = "Posts"
  pageRef = "categories"
  weight = 10

[[main]]
  name = "Tags"
  parent = "Posts"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Resume"
  pageRef = "resume"
  weight = 40
